import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import test from "node:test";
import { applicationTables, importSnapshot, transformUsers, type MigrationSnapshot } from "../../lib/db/migration.ts";
import { decryptVaultSecret, encryptVaultSecret } from "../../lib/vault-crypto.ts";
import { createTestDatabase, databaseTestsEnabled } from "./harness.ts";

test("import is atomic, preserves identity and agent credentials, and refuses a populated target", { skip: !databaseTestsEnabled }, async t => {
  const { connection: target, close } = await createTestDatabase(); t.after(close);
  const id = randomUUID(), profile = randomUUID(), item = randomUUID();
  const auth = transformUsers([{ id, email: "Fixture@EXAMPLE.TEST", encrypted_password: "$2a$10$fixture-hash", email_confirmed_at: new Date().toISOString(), raw_user_meta_data: { full_name: "Provider", display_name: "Custom" } }], [{ user_id: id, provider: "google", provider_id: "provider-subject", identity_data: { sub: "provider-subject" } }]);
  const ciphertext = encryptVaultSecret("fixture", item, profile, "import-fixture-vault-key-at-least-32-characters");
  const snapshot: MigrationSnapshot = { ...auth, tables: Object.fromEntries(applicationTables.map(table=>[table, []])) };
  snapshot.tables.creeds = [{ id: profile, type: "personal", name: "Personal", owner_user_id: id }];
  snapshot.tables.creed_members = [{ creed_id: profile, user_id: id, role: "owner" }];
  snapshot.tables.creed_tokens = [{ user_id: id, read_token_hash: "existing-agent-hash", encrypted_read_token: "existing-agent-ciphertext" }];
  snapshot.tables.creed_headless_access_keys = [{ creed_id: profile, user_id: id, name: "Imported key", key_prefix: "strap_key_imported", key_hash: "imported-headless-hash" }];
  snapshot.tables.creed_vault_items = [{ id: item, creed_id: profile, name: "Key", description: "", secret_ciphertext: ciphertext, created_by: id }];
  snapshot.tables.strap_skills = [{ strap_id: profile, name: "imported-skill", description: "Imported fixture", revision: 1, digest: "a".repeat(64), files: [{ path: "SKILL.md", content: "fixture" }], byte_count: 7, file_count: 1, storage_bytes: 999 }];
  const broken = structuredClone(snapshot);
  const unexpected = structuredClone(snapshot);
  unexpected.tables.creeds[0].unknown_source_column = "must-not-be-lost";
  await assert.rejects(importSnapshot(target, unexpected), /Source columns changed/);
  broken.tables.creed_members[0].user_id = randomUUID();
  await assert.rejects(importSnapshot(target, broken));
  assert.equal((await target`select count(*)::int as count from users`)[0].count, 0);
  const counts = await importSnapshot(target, snapshot);
  assert.equal(counts.users, 1); assert.equal(counts.accounts, 2);
  const [user] = await target`select id,email,display_name from users`;
  assert.equal(user.id, id); assert.equal(user.email, "fixture@example.test"); assert.equal(user.display_name, "Custom");
  const accounts = await target`select provider_id,account_id,password from accounts order by provider_id`;
  assert.equal(accounts[0].password, "$2a$10$fixture-hash"); assert.equal(accounts[1].account_id, "provider-subject");
  const [token] = await target`select read_token_hash,encrypted_read_token from creed_tokens`;
  assert.equal(token.read_token_hash, "existing-agent-hash"); assert.equal(token.encrypted_read_token, "existing-agent-ciphertext");
  const [headless] = await target`select key_hash,vault_item_ids from creed_headless_access_keys`;
  assert.equal(headless.key_hash, "imported-headless-hash"); assert.deepEqual(headless.vault_item_ids, []);
  const [secret] = await target`select secret_ciphertext from creed_vault_items`;
  assert.equal(decryptVaultSecret(secret.secret_ciphertext, item, profile, "import-fixture-vault-key-at-least-32-characters"), "fixture");
  const [skill] = await target`select file_count,storage_bytes,octet_length(files::text) as expected from strap_skills`;
  assert.equal(skill.file_count, 1); assert.equal(skill.storage_bytes, skill.expected);
  await assert.rejects(importSnapshot(target, snapshot), /Destination must be empty/);
});
