-- Make new profile integrations and future Vault descriptions Strap-native.
-- Historical table, column, and function identifiers remain compatibility
-- contracts; this migration changes only customer-facing defaults and prose.

alter table public.creed_version_control
  alter column path set default 'strap.md';

alter table public.creed_company_version_control
  alter column path set default 'strap.md';

-- "Your Creed" was only generated by the personal-shell backfills when no
-- usable account name existed. The equality of created_at and updated_at is the
-- provenance guard: any row subsequently edited by the product is left alone,
-- including a user who intentionally chose the same visible name.
update public.creeds
set
  name = 'Your Strap',
  updated_at = timezone('utc'::text, now())
where type = 'personal'
  and name = 'Your Creed'
  and created_at = updated_at;

create or replace function public.creed_vault_create_secret(
  p_creed_id uuid,
  p_created_by uuid,
  p_name text,
  p_description text,
  p_secret text
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_item_id uuid := gen_random_uuid();
  v_vault_id uuid;
begin
  v_vault_id := vault.create_secret(
    p_secret,
    'creed_' || replace(v_item_id::text, '-', ''),
    'Managed by Strap'
  );

  insert into public.creed_vault_items (
    id, creed_id, vault_secret_id, name, description, created_by
  ) values (
    v_item_id, p_creed_id, v_vault_id, p_name, coalesce(p_description, ''), p_created_by
  );
  return v_item_id;
end;
$$;

revoke all on function public.creed_vault_create_secret(uuid, uuid, text, text, text)
  from public, anon, authenticated;
grant execute on function public.creed_vault_create_secret(uuid, uuid, text, text, text)
  to service_role;
